runs:
  using: "composite"
  steps:
    - name: Install Templates
      run: |
        dotnet new --install ./BepInEx.Templates/templates/
      shell: bash
        
    - name: Test BepInEx5 Template
      if: always()
      run: |
        dotnet new bepinex5plugin --dry-run --diagnostics
      shell: bash