runs:
  using: "composite"
  steps:
    - name: Install Templates
      run: |
        dotnet new --install ./UltraModding.Templates/templates/
      shell: bash
        
    - name: Test Bare Plugin Template
      if: always()
      run: |
        dotnet new ultrakillbareplugin --dry-run --diagnostics
      shell: bash