name: Pack Templates

on: 
  workflow_run:
    workflows: ["Verify Templates"]
    types: [completed]

jobs:
  pack-templates:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Pack templates into .nupkg
    runs-on: ubuntu-latest
    steps: 
      - name: Fetch Sources
        uses: actions/checkout@v4
        
      - name: Setup .NET env
        uses: actions/setup-dotnet@v4
        id: setup-dotnet
        with:
          dotnet-version: 9.x
          dotnet-quality: ga
      - run: |
          dotnet new globaljson --sdk-version ${{ steps.setup-dotnet.outputs.dotnet-version }}

      - name: Pack Templates
        run: |
          cd ./UltraModding.Templates/ 
          dotnet pack -v n
          pwd
          
      - name: Upload Template Package Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          path: "*/nuget/UltraModding.Templates.1.0.0.nupkg"
          compression-level: 0
    
