name: Verify Templates

on:
  push:
  pull_request:
  
jobs:
  test-dotnet-sdk:
    name: Test .NET SDK ${{ matrix.dotnet-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [6.x, 7.x, 8.x, 9.x]
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
          
      - name: Setup .NET env
        uses: actions/setup-dotnet@v4
        id: setup-dotnet
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          dotnet-quality: ga

      - run: |
          dotnet new globaljson --sdk-version ${{ steps.setup-dotnet.outputs.dotnet-version }}

      - name: Dry-run Templates
        uses: ./.github/actions/dryrun-templates